version: '3.8'

services:
  webapi:
    build:
      context: ./
      dockerfile: LiGrow.Blazor.MenuDigital.WebApi/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      API_SECRET_KEY: MZo8TQQm61tTdVnP68MHKU2UHBosFLNR
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network
    ports:
      - "8089:80"

  website:
    build:
      context: ./
      dockerfile: LiGrow.Blazor.MenuDigital.Web/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      API_URL: https://api.menu.tinella.pt
      API_SECRET_KEY: MZo8TQQm61tTdVnP68MHKU2UHBosFLNR
    depends_on:
      - webapi
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network
    ports:
      - "8088:80"

networks:
  app-network:
    driver: bridge